### ISSUE TITLE
请问是否能添加一个许可证

### ISSUE THREAD

**Issue by Hagb** [VayneDuan/CQU-Grade-Monitor#1]
感谢作者的项目！请问能否添加一个许可证，以便他人知道能对这个项目做什么？

**Comment by VayneDuan** [comment]
谢谢提醒, 我已经加上了GPL协议, 但是我初次接触许可证相关, 如果有不当之处, 非常欢迎你的进一步建议

**Comment by Hagb** [comment]
请问是否愿意让这个项目被收录到重庆大学自由/开源软件目录 https://github.com/cqu-codehub/cqu-code-index ？

**Comment by VayneDuan** [comment]
> 请问是否愿意让这个项目被收录到重庆大学自由/开源软件目录 https://github.com/cqu-codehub/cqu-code-index ？ 

没问题的，谢谢你

**Comment by Hagb** [comment]
已收录。感谢！
