### ISSUE TITLE
自动获取课程数量（courseNum)

### ISSUE THREAD

**Issue by Hagb** [VayneDuan/CQU-Grade-Monitor#2]
`work` 函数里有

https://github.com/VayneDuan/CQU-Grade-Monitor/blob/728eb0ea924a97172ab2779d24490bed944b5ca0/cqu_grade_monitor.py#L141

`len(s1) // 9 - 1` 是不是可以获得课程数量？（表格除去表头一行，剩下的行数应该就是课程数，同时每行有 9 列）

**Comment by VayneDuan** [comment]
感谢, 测试没什么问题, 我正在重构一些配置项, 晚些时候会更新版本
