### ISSUE TITLE
运行十个小时，无法ping `my.cqu.edu.cn`，error.log如下

### ISSUE THREAD

**Issue by LiuZhipeng99** [VayneDuan/CQU-Grade-Monitor#7]
init2021-06-25 16:26:26 	第 1 次错误

HTTPConnectionPool(host='my.cqu.edu.cn', port=80): Max retries exceeded with url: /sam-api/score/student/score (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9c092dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))2021-06-25 16:31:26 	第 2 次错误

HTTPConnectionPool(host='my.cqu.edu.cn', port=80): Max retries exceeded with url: /sam-api/score/student/score (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9c03d760>: Failed to establish a new connection: [Errno 111] Connection refused'))2021-06-25 16:36:26 	第 3 次错误

HTTPConnectionPool(host='my.cqu.edu.cn', port=80): Max retries exceeded with url: /sam-api/score/student/score (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9c03d9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))2021-06-25 16:41:27 	第 4 次错误

HTTPConnectionPool(host='my.cqu.edu.cn', port=80): Max retries exceeded with url: /sam-api/score/student/score (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9c08a190>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by pkmq24** [comment]
今天整个my.cqu.edu.cn的网站在下午四点半前后关闭了外网访问
可以在内网环境继续挂机~

**Comment by pkmq24** [comment]
新版本加入了vpn支持 可以继续在服务器快乐挂机了~
